### ISSUE TITLE
IfcOpenCrossProfileDef missing left side of road?

### ISSUE THREAD

**Issue by javierNadal** [bSI-InfraRoom/IFC-infra-unit-test#95]
Hello

In this sample scenario: one simple road with two lanes (3.5m wide), in opposite directions, and alignment in the middle of the road.

I want to build some cross sections with IfcOpenCrossProfileDef, but as Widths attribute is IfcNonNegativeLengthMeasure type, I can only define cross sections at the right side of alignment.

#N=IFCSECTIONEDSOLIDHORIZONTAL(#XXXalignment,(#N+1,#N+2,...), IFCNONNEGATIVELENGTHMEASURE(0.),IFCNONNEGATIVELENGTHMEASURE(20.),...),.F.);
#N+1=IFCOPENCROSSPROFILEDEF(.CURVE.,$,.T.,(-3.5,IFCNONNEGATIVELENGTHMEASURE(3.5)),(0.02,-0.02),('Left','Center','Right'));
That -3.5 is not possible.

I think, it would be nice if this were possible. Maybe with IFCPARAMETERVALUE(-3.5)
Or include an additional optonal parameter to IFCSECTIONEDSOLIDHORIZONTAL to make origin displacement of -3.5, maybe with IFCPOINTBYDISTANCEEXPRESSION,
and then keep IFCNONNEGATIVELENGTHMEASURE(3.5),IFCNONNEGATIVELENGTHMEASURE(3.5)

Just to avoid creating an auxiliary 'top left' alignment.
![image](https://user-images.githubusercontent.com/69001750/113905040-0607cc00-97d3-11eb-8d76-a9cd8166ea56.png)

**Comment by larswik** [comment]
You will need to use IfcPointByDistanceExpression (including LateralOffset) since the profile breakpoints are defined as a sequence using the Widths and Slopes. Either start at one end and go from there or define an IfcCompositeProfileDef from several IfcOpenCrossProfileDef using the Slopes going in different directions from the "origin".
**From documentation of IfcOpenCrossProfileDef:**
A two-dimensional open profile defined by widths and slopes for the use within the swept surface geometry, in SectionedSurface in particular. The underlying coordinate system is defined by the swept surface that uses the profile definition; when used in SectionedSurface it is the XY plane of each list member of SectionedSurface.CrossSectionPositions where the profile X axis is oriented perpendicularly to the left of the Directrix (same direction as positive LateralOffset at IfcPointByDistanceExpression) as facing forward along the directrix, and the profile Y axis is oriented upwards or vertically perpendicular to the Directrix depending on the usage in the SectionedSurface. The behaviour of OpenCrossProfileDef in sweeping operation can be controlled by attribute Tags. Tags allow two consecutive cross sections to have different number of break points: points with the same tag value are connected either by assuming linear longitudinal breakline between them, or by a guide curve identified by the same Tag value as the cross section points. ***Formal propositions: The profile type shall be CURVE.

The list of slopes and the list of widths shall be of the same size, and the list of tags shall have one more member.

![image](https://user-images.githubusercontent.com/25506404/114054612-4d07c700-9890-11eb-887a-de2ffa84153f.png)

**Comment by javierNadal** [comment]
OK. IfcSectionedSurface contains both lists profiles and positions.
I was trying ot use IfcSectionedSolidHorizontal, that changed positions from IfcPointByDistanceExpression to IfcCurveMeasureSelect.
Larswick, thank you very much.
